### ISSUE TITLE
Sequence contains no elements when mapping enums

### ISSUE THREAD

**Issue by GothikX** [agileobjects/AgileMapper#12] opened 2017-05-07 12:21 UTC
So it took me quite a while to figure out what was going on. I was getting this only when I mapped enums:

    System.InvalidOperationException: Sequence contains no matching element
      at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
      at AgileObjects.AgileMapper.TypeConversion.ToStringConverter.GetConversion(Expression sourceValue) in ...ToStringConverter.cs:line 27
    ...

Which was puzzling until I figured out it only happens when the source enum is in a class library targetting .Net Standard. Apparently no public instance methods are returned in this case - don't know much more than that since I'm pretty new at this whole netstandard/netcore thing. I don't even know what would be a sensible approach to take here to make the error more clear, so I'm not going to do a pull request unless you suggest something.

**Comment by GothikX** [comment] 2017-05-07 12:36
Well it's got nothing to do with the targeting of assemblies, now I see DeclaredMethods is used to get the ToString methods. Which won't work because the enum types inherit ToString from the base Enum type.

**Comment by SteveWilkes** [comment] 2017-05-07 12:51
Yeah - I've just spotted the same thing - it's a bug in my [NetStandardPolyfills](https://github.com/agileobjects/NetStandardPolyfills) package. I'm fixing it now and I'll push out a new version later today.

Thanks for the feedback, it's appreciated :)

**Comment by SteveWilkes** [comment] 2017-05-07 13:53
I've now pushed out NetStandardPolyfills [v0.2.1](https://www.nuget.org/packages/AgileObjects.NetStandardPolyfills) - once NuGet publishes the package, updating to that version should fix this issue.

NB: If you're working in partial trust you might encounter an issue with package versions after the update. Otherwise it should be fine :)

**Comment by GothikX** [comment] 2017-05-07 15:48
Awesome, thanks for the prompt response! But now I'm seeing odd behavior with constructors - I think it worked before. If the target of my mapping didn't have a explicit constructor defined, it didn't seem to be constructed (Target was null in After.Call). When I added a public constructor with no parameters, it now throws a MappingException:

    AgileObjects.AgileMapper.MappingException: An exception occurred mapping Account -> AccountResponse with rule set CreateNew. ---> AgileObjects.AgileMapper.MappingException: An exception occurred creating a mapping data instance ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at AgileObjects.AgileMapper.ObjectPopulation.ObjectMappingData`2.set_Mapper(IObjectMapper value)
   at AgileObjects.AgileMapper.ObjectPopulation.MappingDataFactory.ForChild[TSource,TTarget](TSource source, TTarget target, Nullable`1 enumerableIndex, String targetMemberRegistrationName, Int32 dataSourceIndex, IObjectMappingDataUntyped parent)
   at lambda_method(Closure , IObjectMappingData`2 )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , IObjectMappingData`2 )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , IObjectMappingData`2 )
   at AgileObjects.AgileMapper.MappingExecutor`1.PerformMapping[TTarget](MappingRuleSet ruleSet, TTarget target)
   at AgileObjects.AgileMapper.MappingExecutor`1.ToANew[TResult]()
   ...

**Comment by SteveWilkes** [comment] 2017-05-07 16:28
Hmm, that's an odd one - I've updated my NetStandardPolyfills package locally and I can't reproduce it.

Could you either paste the class definitions or files into here, or create a branch with a failing test?

**Comment by GothikX** [comment] 2017-05-07 17:34
Right, once again I rushed to conclusions and then couldn't even replicate what I saw. The hierarchy of objects I work with is complex and I'm still trying to reproduce that exact exception in a unit test; it might have something to do with classes with the same name in different namespaces and assemblies, derived from the same base class, and selection of constructors...

In my plan for the top level mapping I have two sections, and the second section seems to be a mapping from a type to... the very same type. Reproducing the barebones class structure in a unit test doesn't do this so maybe you have some idea as to what could cause this?

**Comment by SteveWilkes** [comment] 2017-05-07 18:06
It's hard to say without seeing the types or the mapping plan, really. If it doesn't consistently fall down then it could be a particular combination of base-typed properties being populated with derived types, but I can't think what that combination would be or why it would cause an issue.

Regarding the mapping plan - if the object structure doesn't include mapping between properties of those types then that's a bug I'd like to look at.

**Comment by SteveWilkes** [comment] 2017-05-07 18:40
I'm going to close this issue as it originally related to the .NET Standard Enum.ToString() error - please feel free to open another issue if you can reproduce the constructor error or want to add the class structures or mapping plan :)

**Closed by SteveWilkes** 2017-05-07 18:40 UTC
