### ISSUE TITLE
Unable to deep clone an Image object

### ISSUE THREAD

**Issue by vsederburg** [agileobjects/AgileMapper#180] opened 2019-12-07 16:32 UTC
I have an attribute called "[DirtyCheck]" that I apply to dto properties that I want monitored for changes that otherwise wouldn't be.  Normally I only have to use this once on a give DTO, but I just ran across one that needs it multiple times.  Apparently the DeepClone doesn't like that and throws an argument exception "An item with the same key has already been added."

To be clear, this is not a case of using the same attribute multiple times on the SAME property. I'm using the same attribute multiple times within the class, on different properties.

Stack track attached.

[stacktrace.txt](https://github.com/agileobjects/AgileMapper/files/3935290/stacktrace.txt)

Love your product!
Thanks for any help.

**Comment by vsederburg** [comment] 2019-12-07 16:34
Oh, I'm using the latest preview release 1.6.0-preview5

**Comment by vsederburg** [comment] 2019-12-07 17:00
Ok I've narrowed it down better.  I was sure it was the duplicate attribute because I'd had that error months ago and had worked around it, but after I posted this I realized I hadn't tried removing them to see if it eliminated the error.

I can now verify that it doesn't seem to be attribute related. I think it has something to do with the fields/properties themselves, but I can't figure it out.

I have two private image fields, and one public image property that returns one or the other of the private images:

private readonly Image _failImage = Images.IconFailure16;
private readonly Image _successImage = Images.IconSuccess16;
public Image ErrorImage => IsError ? _failImage : _successImage;

If I comment out the public ErrorImage property, the DeepClone works fine. Otherwise it fails. It acts like it's reading the property and seeing the field names and thinking it's a duplicate declaration of some sort.  

HOWEVER, it also fails if I remove the two private fields and change it to just a single property!
public Image ErrorImage => IsError ? Images.IconFailure16 : Images.IconSuccess16;

Hope that helps, sorry for the confusion. Let me know if I can provide any other details.

**Comment by SteveWilkes** [comment] 2019-12-07 20:38
Hi!

Thanks for the info - please could you copy / paste me the entire class definition?

Cheers,

Steve

**Comment by vsederburg** [comment] 2019-12-07 22:22
Ok, EmailRecipientDto is the one I'm trying to DeepClone.
Also attached the basic Images class in case that matters.

[EmailRecipientDto.txt](https://github.com/agileobjects/AgileMapper/files/3935622/EmailRecipientDto.txt)
[Images.txt](https://github.com/agileobjects/AgileMapper/files/3935623/Images.txt)

**Comment by SteveWilkes** [comment] 2019-12-08 08:10
Thanks! I've made [a dotnetfiddle](https://dotnetfiddle.net/uh7E3k) where we can figure this out - I've added the `EmailRecipientDto` class, a basic `BaseDto` class, an empty `Image`, then made it write out the mapping plan - no error yet. I've removed the attributes because I don't think that's what's causing the problem - I suspect it's an issue with `Image`. Is `Image` from the BCL, or is it one of yours?

Could you update the fiddle to reproduce the issue?

**Comment by vsederburg** [comment] 2019-12-08 20:56
Sorry, I replied to the email, but I'm not sure if that goes anywhere. Here it is again:

I tried to use the dotnetfiddle, but I can't figure out how to modify it.  First thing I noticed is that my application is not .net core, it's a winforms app using .net framework 4.7.2.

When I change to 4.7.2 on dotnetfiddle, I lose everything and it won't let me reselect the agilemapper nuget package for some reason.

The image is a system.drawing.image file. A standard .png file I created. I've attached those if it helps.

![StatusFail_16x16](https://user-images.githubusercontent.com/34285284/70396039-b640a700-19ca-11ea-9084-75a7b8c275ba.png)
![StatusOk_16x16](https://user-images.githubusercontent.com/34285284/70396043-ba6cc480-19ca-11ea-8e8e-66408860f432.png)

Also, here are the properties that are in DtoBase, and ObservableObject (I'm assuming it's only properties that matter)


public class DtoBase : ObservableObject, IDto
{

private bool _isDirty;
public bool IsDirty
{
    get => _isDirty;
    set
    {
        if (_isDirty == value)
            return;

        _isDirty = value;

        RaisePropertyChanged(nameof(IsDirty));
    }
}

public static Dictionary<Type, DtoClassMetadata> MetadataDictionary { get; set; }
public Dictionary<string, object> OriginalPropertyValues { get; set; }
public bool IsLinkedToDatabase { get; set; }

}


public class ObservableObject : INotifyPropertyChanged
{
    private PropertyInfo[] _properties;
    public PropertyInfo[] Properties => _properties ??
                                        (_properties = GetType().GetProperties(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public));


    protected PropertyChangedEventHandler PropertyChangedHandler => PropertyChanged;
    public event PropertyChangedEventHandler PropertyChanged;
}    
```

**Comment by vsederburg** [comment] 2019-12-08 20:58
Ok, I plainly can't make this insert code correctly. :)

**Comment by SteveWilkes** [comment] 2019-12-09 16:17
Ok! I've [reproduced it](https://dotnetfiddle.net/B8nJV0) - it's simply a problem trying to deep clone the `ErrorImage` property. It shouldn't even be trying - given that `ErrorImage` is readonly - so I'll sort that out.

In the meantime, you can workaround the issue by ignoring the `ErrorImage` property, like [this](https://dotnetfiddle.net/ZWT0KB).

Cheers!

Steve

**Comment by vsederburg** [comment] 2019-12-10 01:49
Ah, excellent, excluding that property does allow the deepclone to work.  Glad you were able to reproduce it.

**Comment by Alysaar** [comment] 2019-12-19 16:15
I have had a similar issue in my code. I have found a fix but in case it is usefull to you :
[Here is my example](https://dotnetfiddle.net/yHKT4k) after I have reduced it as much as I could.
I was expecting a `MappingValidationException` but something went wrong inside AgileMapper causing a different error.

In my case the problem only occurs when the mapping plan is incomplete (I use the `mapper.WhenMapping.ThrowIfAnyMappingPlanIsIncomplete();` option), so it was not a big issue, I just had to make my mapping complete, it just took a while to track where the error was coming from.

Hope this helps.

**Comment by SteveWilkes** [comment] 2020-02-18 08:51
This issue was found cloning a `System.Drawing.Image` object when derived types were being auto-discovered and the mapper was trying to figure out mappings _from_ any Image-derived type _to_ any Image-derived type. It found a recursive relationship deep within one of those mappings and fell over.

Auto-discovery of derived types is now switched off, and this bug hasn't shown itself anywhere else, so I'm going to close this issue there.

**Closed by SteveWilkes** 2020-02-18 08:51 UTC
Labels: bug
